version: "3"
name: valheim
services:
  valheim-darkness:
    container_name: valheim-darkness
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes:
      - ./config:/config
      - ./server:/opt/valheim
    ports:
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    env_file:
      - ./private.env
      - ./public.env
    restart: always
    stop_grace_period: 2m
  discord-lilluna:
    container_name: discord-lilluna
    build:
      context: discord
      dockerfile: Dockerfile
    volumes:
      - /home/nemkin/Git/valheim/server/htdocs:/valheim
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./private.env
      - ./public.env
    restart: always

