version: "3"
name: valheim
services:
  valheim:
    container_name: valheim-server
    image: valheim-server-local
    cap_add:
      - sys_nice
    volumes:
      - ./config:/config
      - ./server:/opt/valheim
    ports:
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    env_file:
      - ./private.env
      - ./public.env
    depends_on:
      - log-server
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "valheim/{{.Name}}/{{.ID}}"
    restart: always
    stop_grace_period: 2m
  discord-lilluna:
    container_name: discord-lilluna
    build:
      context: discord
      dockerfile: Dockerfile
    volumes:
      - /home/nemkin/Git/valheim/server/htdocs:/valheim
    env_file:
      - ./private.env
      - ./public.env
    restart: always

