version: "3"
name: valheim
services:
  valheim:
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes:
      - /home/nemkin/Data/valheim/config:/config
      - /home/nemkin/Data/valheim/data:/opt/valheim
    ports:
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    env_file:
      - ./private.env
      - ./public.env
    restart: always
    stop_grace_period: 2m

