Everyone:
  name: Everyone
  gear: {}
  crafted: {}
-1343676718:
  name: Luna
  player: Steam_76561198091638262
  helmet: HelmetFenring
  shoulder: None
  chest: ArmorFenringChest
  legs: ArmorFenringLegs
  gear: {}
  crafted: {}
923534657:
  name: Fream
  player: Steam_76561198065605988
  gear: {}
  crafted: {}
2472803686:
  name: Jösur
  player: Steam_76561198127814636
  gear: {}
  crafted: {}
