Everyone:
  name: Everyone
  gear: {}
  crafted: {}
923534657:
  name: Fream
  player: Steam_76561198065605988
  gear: {}
  crafted: {}
2472803686:
  name: Jösur
  player: Steam_76561198127814636
  gear: {}
  crafted: {}
-964017334:
  name: Luna
  player: Steam_76561198091638262
  helmet: None
  shoulder: None
  chest: ArmorLeatherChest
  legs: ArmorLeatherLegs
  gear: {}
  crafted: {}
